### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bruno77689** [mhdzumair/RevolX#1]
I'm getting this error can you help me?

 `fucking: vuexybux
Traceback (most recent call last):
  File "C:\Users\bruno1\Downloads\RevolX-main1\RevolX-main\revolvx.py", line 144, in <module>
    revolvx = RevolvX(site.get("name"), site[0].text, site[1].text)
  File "C:\Users\bruno1\Downloads\RevolX-main1\RevolX-main\revolvx.py", line 45, in __init__
    self.firefox = webdriver.Firefox(executable_path=geckodriver, options=options)
  File "C:\Users\bruno1\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\bruno1\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\bruno1\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\bruno1\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\bruno1\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\bruno1\AppData\Local\Programs\Python\Python39\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by mhdzumair** [comment]
Hey @bruno77689  make sure you have Firefox installed in your PC. Also, please note, this vuexybux and other sites are set google captcha verification on login page after I publish these codes. But still you can get benefit with Ads Fucker Firefox extension. Thanks for trying this project.
